add request model and requests top
hiddenSt/Base pull request #4
Opened 2021-02-28 18:02 UTC by boyboyjoy

2021-02-28 18:13 UTC, hiddenSt commented
Я не уверен использования реляционной БД, я посмотрел бы в сторону NoSQL, например Neo4j.

2021-02-28 18:24 UTC, hiddenSt commented on Base/models/request_model.py
> +class Request(models.Model):
Мне не нравится название класса, оно пересекается с названием стандартным названием класса Request в  django.

2021-02-28 18:24 UTC, hiddenSt commented on Base/services/top_requests.py
> +def get_top():
Почему эта функция вне класса?

2021-02-28 18:28 UTC, boyboyjoy commented on Base/services/top_requests.py
> +def get_top():
Ассоцитивно невозможно объединить на даный момент с каким либо классом.

2021-02-28 18:30 UTC, hiddenSt commented on Base/models/request_model.py
>      time = models.DateTimeField(auto_created=True, auto_now_add=True)
Я бы назвал timestamp

2021-02-28 18:35 UTC, hiddenSt commented
Добавь, пожалуйста, тесты

2021-03-12 13:14 UTC, hiddenSt requested changes
А тесты где?

2021-03-13 06:42 UTC, boyboyjoy commented
> 
> 
> А тесты где?

было бы что тестировать.........

2021-03-13 06:45 UTC, hiddenSt commented
> > А тесты где?
> 
> было бы что тестировать.........

функцию get_top

2021-03-15 03:26 UTC, hiddenSt commented on Base/tests/test_top_requests.py
> +        print(get_top(), request_dict)
Зачем print в тесте?

2021-03-15 03:28 UTC, hiddenSt commented on Base/tests/test_top_requests.py
> +        request_dict.setdefault('123', 1)
В отдельные переменные я бы вынес элементы dict, чтобы менять возможные значения в одном месте, а не в dict и Model. Мало ли опечатка и тест из-за неё повалиться.

2021-03-15 03:30 UTC, hiddenSt commented on Base/serializers/request_serializer.py
> +        fields = ['time', 'text', 'user']
У модели нет поля ```time```, есть ```timestamp```

2021-03-15 03:34 UTC, hiddenSt requested changes
Да и тестов бы побольше. Один тест ```test_top_request_logic```, который проверяет все аспекты модуля, не очень удобен при дебаге и фиксе ошибок.

- [x] Исправить замечания

- [ ] Добавить больше тестов

2021-03-15 03:42 UTC, hiddenSt commented
Вынеси, пожалуйста, всё в отдельный модуль.

2021-03-15 05:22 UTC, boyboyjoy commented
> 
> 
> Вынеси, пожалуйста, всё в отдельный модуль.

????????????????????????

2021-03-15 05:24 UTC, boyboyjoy commented on Base/tests/test_top_requests.py
> +        request_dict.setdefault('123', 1)
> 
> 
> Да и тестов бы побольше. Один тест `test_top_request_logic`, который проверяет все аспекты модуля, не очень удобен при дебаге и фиксе ошибок.
> 
>     * [ ]  Исправить замечания
> 
>     * [ ]  Добавить больше тестов
одна функция = один тест

2021-03-15 05:27 UTC, hiddenSt commented
> > Вынеси, пожалуйста, всё в отдельный модуль.
> 
> ????????????????????????

---Base
|
|
----TopRequests
|
|
| 
---manage.py

2021-03-15 05:27 UTC, boyboyjoy commented
> 
> 
> > > Вынеси, пожалуйста, всё в отдельный модуль.
> > 
> > 
> > ????????????????????????
> 
> ---Base
> |
> |
> ----TopRequests
> |
> |
> |
> ---manage.py

зачем для 1 функции делать отдельное приложение ...................

2021-03-15 05:29 UTC, hiddenSt commented
Нет, это нужно сделать сразу

2021-03-15 05:40 UTC, boyboyjoy commented
> 
> 
> Нет, это нужно сделать сразу

2021-04-15 06:06 UTC, hiddenSt requested changes
Добавь тесты, пожалуйста.

2021-04-29 01:26 UTC, hiddenSt requested changes
Норм, только поправь замечания.

2021-04-29 01:26 UTC, hiddenSt commented on Base/google_api/google_api.py
> +        return json.dumps(all_books)
Я же говорил, что не нужно ничего преобразовывать в json. Возвращай обычный dict.

2021-04-29 01:26 UTC, hiddenSt commented on Base/google_api/google_api.py
> +        book_data = json.loads(book_data)
Создавай обычный dict

2021-04-29 01:26 UTC, hiddenSt commented on Base/youtube_api/tests/test_youtube_api_wrapper.py
> +        self.assertTrue(self.wrapper.youtube_channel_list_data)
?

2021-04-29 01:26 UTC, hiddenSt commented on Base/youtube_api/tests/test_youtube_api_wrapper.py
> +    def test_search_channels(self):
Название теста не информативно? Какой аспект он проверяет?

2021-04-29 01:26 UTC, hiddenSt commented on Base/youtube_api/youtube_api_wrapper.py
> +        return json.dumps(youtube_data, indent=4)
Опять же, не нужно возвращать json, возвращай всегда dict. Преобразование в json - это дело последнее

2021-04-29 08:27 UTC, boyboyjoy commented on Base/tests/test_top_requests.py
> +        print(get_top(), request_dict)
Не рабочий тест, забыл выпилить

2021-04-29 08:27 UTC, boyboyjoy commented on Base/youtube_api/youtube_api_wrapper.py
> +        return json.dumps(youtube_data, indent=4)
Этот модуль вообще полностью рефакторить надо, я его запукшил, чтобы ты показать мог если надо будет

2021-04-29 08:34 UTC, boyboyjoy commented on Base/youtube_api/tests/test_youtube_api_wrapper.py
> +        self.assertTrue(self.wrapper.youtube_channel_list_data)
Проверяет, что обертка получает ответ от сервера ( не None)

2021-04-29 08:34 UTC, boyboyjoy commented on Base/google_api/google_api.py
> +        book_data = json.loads(book_data)
Ок

2021-04-29 08:34 UTC, boyboyjoy commented on Base/google_api/google_api.py
> +        return json.dumps(all_books)
Хорошо !!!

2021-05-05 13:01 UTC, merged