Fmd
hiddenSt/Base pull request #6
Opened 2021-04-14 18:08 UTC by FieldmarshalDub

2021-04-15 06:04 UTC, hiddenSt requested changes
Добавь тесты, пожалуйста.

2021-04-15 06:04 UTC, hiddenSt commented on TelegramApiWrapper/telegram_api_wrapper.py
> +        api_id = '1825907'
Я бы в какой-нибудь конфиг вынес(.env например)

2021-04-15 06:04 UTC, hiddenSt commented on TelegramApiWrapper/telegram_api_wrapper.py
> +        self.phone = '+79131173447'
Тоже самое замечание

2021-04-15 06:04 UTC, hiddenSt commented on TelegramApiWrapper/telegram_api_wrapper.py
> +        channels_json = json.dumps(channel_list, indent=4)
Не стоит переводить сразу в json, лучше возвращай питоновские структуры данных. А преобразование в json это уже дело последнее

2021-04-15 06:28 UTC, FieldmarshalDub commented on TelegramApiWrapper/telegram_api_wrapper.py
> +        api_id = '1825907'
Я знаю, так и было раньше, просто из init-а почему то не видно файл с настройками

2021-04-15 06:29 UTC, hiddenSt commented on TelegramApiWrapper/telegram_api_wrapper.py
> +        api_id = '1825907'
ок, понял

2021-04-28 15:05 UTC, hiddenSt commented on TelegramApiWrapper/tests/test_telegram_wrapper.py
> +        result = self.telegram.search_channels("python")
Текст запроса вынести в одну переменную
```python
 query = "python"
result = self.telegram.search_channels(query)
...
if result[0]['title'].find(query):
            result_b = True
        self.assertTrue(result_b)
```

2021-04-28 15:06 UTC, hiddenSt requested changes
Please  refactor

2021-05-05 13:03 UTC, merged